version: '3.8'

services:
  db:
    image: postgres:13
    container_name: sicredi_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sicredi_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
